### ISSUE TITLE
Cabal file links to vec instead of dec

### ISSUE THREAD

**Issue by jlwoodwa** [phadej/dec#2]
The `homepage` and `bug-reports` fields of the Cabal file erroneously link to https://github.com/phadej/vec instead of https://github.com/phadej/dec.

**Comment by phadej** [comment]
Good catch. `dec` was previously inside `vec`'s repository. I'll update the rest of the links.

**Comment by phadej** [comment]
Done as part of https://github.com/phadej/dec/pull/3
